# Generated by Django 3.1.4 on 2020-12-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogue', '0003_auto_20201221_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photometadata',
            name='shootDate',
            field=models.DateTimeField(help_text='Date when photo was taken', null=True),
        ),
    ]
